// export const DISPLAYPRODUCTS = 'DISPLAYPRODUCTS';
export const GET_PRODUCT = "GET_PRODUCT";
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const GET_POPULAR_PRODUCT = "GET_POPULAR_PRODUCT";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";